### ISSUE TITLE
Add a cachehash_del() function

### ISSUE THREAD

**Issue by hiqsociety** [zakird/cachehash#1]
can you provide a cachehash_del() function?

how do u delete a key? coz put does not override BUT throws error for same key

**Comment by dadrian** [comment]
We would accept a PR for this function.

**Comment by typzzh** [comment]
> can you provide a cachehash_del() function?
> 
> how do u delete a key? coz put does not override BUT throws error for same key

I did not find this function, where is it? Thanks ！
