### ISSUE TITLE
possible to convert this to char[] instead of void* (char*)?

### ISSUE THREAD

**Issue by hiqsociety** [zakird/cachehash#3]
possible to convert this to char[] instead of void* (char*)?

doing so will reduce memory usage by not having to keep keylen.

any reasons why didnt it start with char[] instead? coz str is very limited. (need to use strlen which is not very byte friendly for other data)

great work by the way.

**Comment by zakird** [comment]
I unfortunately don't understand what you're asking in this issue. To be quite honest, I'm not sure even if you're in the right project. There aren't any character pointers or strings in this codebase.

**Comment by hiqsociety** [comment]
because there is strlen() which terminates on "0"
i'm writing a golang binding for this and GoBytes has {1,2,3,0,4,5} values and when C sees a 0, it is terminated.

i've gotten it halfway done but i realised you have keylen <- i'm not proficient in C but if we use char[], wont that make keylen unnecessary?

the strlen is in test.c file.

not sure how to store pure bytes as in golang's []byte


after i wrote the replace function, the pointer value cannot store anything lesser than 4 bytes without appending garbage information to the value.

have you tried storing things that are lesser than 4 bytes? the results gotten back will not match the expected output when i clear the key and replace with new values.

**Comment by zakird** [comment]
This still does't make sense. Arrays in C don't have lengths that you can detect like that -- so no, it doesn't. If you pass a char[] into a function, the function has no idea the length of the array. Why don't you use the version of this library that we've written in Go? https://github.com/zmap/zdns/blob/master/cachehash/cachehash.go

**Comment by hiqsociety** [comment]
@zakird ok i've re-checked all my code, was my issue. i didnt grasp c properly. now i do. it's great piece of software!

really like it a lot. thx for the hard work.

everything works now. good work on the golang one too
